#ifndef GerenciadorErros

enum {

    ERROPRINCIPAL = 1,
    ERRO_FUNC_ATRIB = 2,
    FUNCAO_N_DECLARADA = 3,
    VAR_N_DECLARADA = 4,
    FUNCAOTOPO = 5,
    QTDPARAM_INCOMPATIVEL = 6,
    TIPOPARAM_INCOMPATIVEL = 7,
    FUNC_RET_VALOR = 8,
    TIPO_INCOMPATIVEL = 9,
    REDECLARACAO = 10,
    REDECLARACAO_PROTO = 11,
    TIPO_FUNC_DIF = 12,
    NOME_PAR_DIF = 13,
    TIPO_DIF = 14,
    ID_ESPERADO = 15,
    PR_ESPERADO = 16,
    FUNCAO_SEMPARAM_PAR = 17,
    PARAM_ESPERADO = 18,
    ERRO_LINHA = 19,
    EXPR_BOOL = 20,
    FECHAPAR_ESPERADO = 21,
    ABREPAR_ESPERADO = 22,
    PTOVIRG_ESPERADO = 23,
    FUNCAO_SEMR_R = 24,
    FUNCAO_RETORNO = 25,
    FUNCAO_SEMRETORNO = 26,
    OPREL_ESPERADO = 27,
    TIPOVAR_ATRIB = 28,
    IGUAL_ESPERADO = 29,
    FUNCAO_DECL_SEMRETORNO = 30,
    VAR_SEMRETORNO = 31,
    ABRECHAVE_ESPERADO = 32,
    FECHACHAVE_SOLTO = 33
};

void GerenciadorErros(int);
#endif
